In [11]:
print("ehllo")

ehllo

In [12]:
import pandas as pd

In [13]:
file = pd.read_csv("d1.csv")

C:\Users\HP\AppData\Local\Temp\ipykernel_7888\4040621763.py:1: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  file = pd.read_csv("d1.csv")

In [14]:
file

,Unnamed: 0,TWEET,STOCK,DATE,LAST_PRICE,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,PX_VOLUME,VOLATILITY_10D,VOLATILITY_30D,LSTM_POLARITY,TEXTBLOB_POLARITY,MENTION
0,0,RT @robertoglezcano: @amazon #Patents Show Fl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Amazon,31/01/2017,823.48,0.008379,0.014924,0.014924,-0.001263,3.137196e+06,13.447,16.992,1.000,0.0,@amazon,NaN
2,1,@FAME95FM1 Jamaicans make money with @Payoneer...,PayPal,31/01/2017,39.780000,0.002011,0.012318,0.012318,5.480141e-02,9100057.000,18.769,16.099,-1,0.0,@PayPal
3,2,@CBSi Jamaicans make money with @Payoneer @Pay...,PayPal,31/01/2017,39.780000,0.002011,0.012318,0.012318,5.480141e-02,9100057.000,18.769,16.099,1,0.0,@PayPal
4,3,@Hitz92fm Jamaicans make money with @Payoneer ...,PayPal,31/01/2017,39.780000,0.002011,0.012318,0.012318,5.480141e-02,9100057.000,18.769,16.099,-1,0.0,@PayPal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143277,861723,https://t.co/IsS8FGekqH: New Releases - Amazon...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143278,NaN,Amazon,30/09/2018,2003.0,0.000000,0.000000,0.004983,-0.043929,4.085135e+06,20.709,22.946,1.000,0.13636363636363635,@amazon,NaN
143279,861864,RT @Google: With hands-free ordering from your...,Google,30/09/2018,1207.080000,0.000000,0.000000,0.000232,-2.896245e-02,1780759.000,15.005,17.588,1,0.0,@Google
143280,862071,Homegate with Lipton® Iced Tea from Walmart th...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143281,NaN,Walmart,30/09/2018,93.91,0.000000,0.000000,0.002343,0.021191,6.306274e+06,8.702,11.667,-1.000,0.0,@Walmart,NaN

In [15]:
file = file.drop(["DATE","LAST_PRICE", "PX_VOLUME",	"VOLATILITY_10D", 	"VOLATILITY_30D",	"TEXTBLOB_POLARITY",	"MENTION"], axis=1)

In [16]:
file

,Unnamed: 0,TWEET,STOCK,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,LSTM_POLARITY
0,0,RT @robertoglezcano: @amazon #Patents Show Fl...,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Amazon,31/01/2017,0.014924,0.014924,-0.001263,3.137196e+06,0.0
2,1,@FAME95FM1 Jamaicans make money with @Payoneer...,PayPal,0.002011,0.012318,0.012318,5.480141e-02,-1
3,2,@CBSi Jamaicans make money with @Payoneer @Pay...,PayPal,0.002011,0.012318,0.012318,5.480141e-02,1
4,3,@Hitz92fm Jamaicans make money with @Payoneer ...,PayPal,0.002011,0.012318,0.012318,5.480141e-02,-1
...,...,...,...,...,...,...,...,...
143277,861723,https://t.co/IsS8FGekqH: New Releases - Amazon...,NaN,NaN,NaN,NaN,NaN,NaN
143278,NaN,Amazon,30/09/2018,0.000000,0.004983,-0.043929,4.085135e+06,0.13636363636363635
143279,861864,RT @Google: With hands-free ordering from your...,Google,0.000000,0.000000,0.000232,-2.896245e-02,1
143280,862071,Homegate with Lipton® Iced Tea from Walmart th...,NaN,NaN,NaN,NaN,NaN,NaN
143281,NaN,Walmart,30/09/2018,0.000000,0.002343,0.021191,6.306274e+06,0.0

In [17]:
file = file.dropna()

In [18]:
file

,Unnamed: 0,TWEET,STOCK,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,LSTM_POLARITY
2,1,@FAME95FM1 Jamaicans make money with @Payoneer...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
3,2,@CBSi Jamaicans make money with @Payoneer @Pay...,PayPal,0.002011,0.012318,0.012318,0.054801,1
4,3,@Hitz92fm Jamaicans make money with @Payoneer ...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
11,7,"RT @nikitakhara: Thank you, @Starbucks CEO for...",Starbucks,0.012314,0.016298,0.016298,0.058312,1
20,12,@gawker Jamaicans make money with @Payoneer @P...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
...,...,...,...,...,...,...,...,...
143251,857260,"RT @Microsoft: Announced at #MSIgnite: @Adobe,...",Microsoft,0.000000,0.000350,-0.003410,-0.000962,-1
143252,857442,@KenDilanianNBC @Starbucks Great idea!!! \r\r\...,Starbucks,0.000000,0.008797,0.007565,0.010732,1
143259,858460,"RT @BMW: Future proof technology, ensuring max...",BMW,0.000000,0.016903,0.014710,0.106194,1
143276,861648,RT @JanetCBrennan: OUT NOW!\r\r\r\r\r\r\nBarne...,Amazon,0.000000,0.000000,0.004983,-0.043929,1
143279,861864,RT @Google: With hands-free ordering from your...,Google,0.000000,0.000000,0.000232,-0.028962,1

In [19]:
file.drop(["Unnamed: 0"], axis=1)

,TWEET,STOCK,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,LSTM_POLARITY
2,@FAME95FM1 Jamaicans make money with @Payoneer...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
3,@CBSi Jamaicans make money with @Payoneer @Pay...,PayPal,0.002011,0.012318,0.012318,0.054801,1
4,@Hitz92fm Jamaicans make money with @Payoneer ...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
11,"RT @nikitakhara: Thank you, @Starbucks CEO for...",Starbucks,0.012314,0.016298,0.016298,0.058312,1
20,@gawker Jamaicans make money with @Payoneer @P...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
...,...,...,...,...,...,...,...
143251,"RT @Microsoft: Announced at #MSIgnite: @Adobe,...",Microsoft,0.000000,0.000350,-0.003410,-0.000962,-1
143252,@KenDilanianNBC @Starbucks Great idea!!! \r\r\...,Starbucks,0.000000,0.008797,0.007565,0.010732,1
143259,"RT @BMW: Future proof technology, ensuring max...",BMW,0.000000,0.016903,0.014710,0.106194,1
143276,RT @JanetCBrennan: OUT NOW!\r\r\r\r\r\r\nBarne...,Amazon,0.000000,0.000000,0.004983,-0.043929,1
143279,RT @Google: With hands-free ordering from your...,Google,0.000000,0.000000,0.000232,-0.028962,1

In [24]:
file = file.rename(columns={"SENTIMENT": "POLARITY"})

In [25]:
file

,Unnamed: 0,TWEET,STOCK,1_DAY_RETURN,2_DAY_RETURN,3_DAY_RETURN,7_DAY_RETURN,POLARITY
2,1,@FAME95FM1 Jamaicans make money with @Payoneer...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
3,2,@CBSi Jamaicans make money with @Payoneer @Pay...,PayPal,0.002011,0.012318,0.012318,0.054801,1
4,3,@Hitz92fm Jamaicans make money with @Payoneer ...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
11,7,"RT @nikitakhara: Thank you, @Starbucks CEO for...",Starbucks,0.012314,0.016298,0.016298,0.058312,1
20,12,@gawker Jamaicans make money with @Payoneer @P...,PayPal,0.002011,0.012318,0.012318,0.054801,-1
...,...,...,...,...,...,...,...,...
143251,857260,"RT @Microsoft: Announced at #MSIgnite: @Adobe,...",Microsoft,0.000000,0.000350,-0.003410,-0.000962,-1
143252,857442,@KenDilanianNBC @Starbucks Great idea!!! \r\r\...,Starbucks,0.000000,0.008797,0.007565,0.010732,1
143259,858460,"RT @BMW: Future proof technology, ensuring max...",BMW,0.000000,0.016903,0.014710,0.106194,1
143276,861648,RT @JanetCBrennan: OUT NOW!\r\r\r\r\r\r\nBarne...,Amazon,0.000000,0.000000,0.004983,-0.043929,1
143279,861864,RT @Google: With hands-free ordering from your...,Google,0.000000,0.000000,0.000232,-0.028962,1